// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializeagentUserJoinSessionContent")
public inline fun agentUserJoinSessionContent(block: AgentUserJoinSessionContentKt.Dsl.() -> kotlin.Unit): IMMsg.AgentUserJoinSessionContent =
  AgentUserJoinSessionContentKt.Dsl._create(IMMsg.AgentUserJoinSessionContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `AgentUserJoinSessionContent`
 */
public object AgentUserJoinSessionContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.AgentUserJoinSessionContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.AgentUserJoinSessionContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.AgentUserJoinSessionContent = _builder.build()

    /**
     * ```
     * 客服昵称
     * ```
     *
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.username
      @JvmName("setUsername")
      set(value) {
        _builder.username = value
      }
    /**
     * ```
     * 客服昵称
     * ```
     *
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * ```
     * 头像
     * ```
     *
     * `string faceUrl = 2;`
     */
    public var faceUrl: kotlin.String
      @JvmName("getFaceUrl")
      get() = _builder.faceUrl
      @JvmName("setFaceUrl")
      set(value) {
        _builder.faceUrl = value
      }
    /**
     * ```
     * 头像
     * ```
     *
     * `string faceUrl = 2;`
     */
    public fun clearFaceUrl() {
      _builder.clearFaceUrl()
    }

    /**
     * ```
     * 加入时间(毫秒)
     * ```
     *
     * `int64 joinTime = 3;`
     */
    public var joinTime: kotlin.Long
      @JvmName("getJoinTime")
      get() = _builder.joinTime
      @JvmName("setJoinTime")
      set(value) {
        _builder.joinTime = value
      }
    /**
     * ```
     * 加入时间(毫秒)
     * ```
     *
     * `int64 joinTime = 3;`
     */
    public fun clearJoinTime() {
      _builder.clearJoinTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.AgentUserJoinSessionContent.copy(block: AgentUserJoinSessionContentKt.Dsl.() -> kotlin.Unit): IMMsg.AgentUserJoinSessionContent =
  AgentUserJoinSessionContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

