// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializecreateSessionContent")
public inline fun createSessionContent(block: CreateSessionContentKt.Dsl.() -> kotlin.Unit): IMMsg.CreateSessionContent =
  CreateSessionContentKt.Dsl._create(IMMsg.CreateSessionContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `CreateSessionContent`
 */
public object CreateSessionContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.CreateSessionContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.CreateSessionContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.CreateSessionContent = _builder.build()

    /**
     * ```
     * 客户接入时间(毫秒)
     * ```
     *
     * `int64 joinTime = 1;`
     */
    public var joinTime: kotlin.Long
      @JvmName("getJoinTime")
      get() = _builder.joinTime
      @JvmName("setJoinTime")
      set(value) {
        _builder.joinTime = value
      }
    /**
     * ```
     * 客户接入时间(毫秒)
     * ```
     *
     * `int64 joinTime = 1;`
     */
    public fun clearJoinTime() {
      _builder.clearJoinTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.CreateSessionContent.copy(block: CreateSessionContentKt.Dsl.() -> kotlin.Unit): IMMsg.CreateSessionContent =
  CreateSessionContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

