// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializeendSessionMsg")
public inline fun endSessionMsg(block: EndSessionMsgKt.Dsl.() -> kotlin.Unit): IMMsg.EndSessionMsg =
  EndSessionMsgKt.Dsl._create(IMMsg.EndSessionMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `EndSessionMsg`
 */
public object EndSessionMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.EndSessionMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.EndSessionMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.EndSessionMsg = _builder.build()

    /**
     * `string sessionID = 1;`
     */
    public var sessionID: kotlin.String
      @JvmName("getSessionID")
      get() = _builder.sessionID
      @JvmName("setSessionID")
      set(value) {
        _builder.sessionID = value
      }
    /**
     * `string sessionID = 1;`
     */
    public fun clearSessionID() {
      _builder.clearSessionID()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.EndSessionMsg.copy(block: EndSessionMsgKt.Dsl.() -> kotlin.Unit): IMMsg.EndSessionMsg =
  EndSessionMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

