// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializerankingContent")
public inline fun rankingContent(block: RankingContentKt.Dsl.() -> kotlin.Unit): IMMsg.RankingContent =
  RankingContentKt.Dsl._create(IMMsg.RankingContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RankingContent`
 */
public object RankingContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.RankingContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.RankingContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.RankingContent = _builder.build()

    /**
     * ```
     * 排名
     * ```
     *
     * `int32 number = 1;`
     */
    public var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.number
      @JvmName("setNumber")
      set(value) {
        _builder.number = value
      }
    /**
     * ```
     * 排名
     * ```
     *
     * `int32 number = 1;`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.RankingContent.copy(block: RankingContentKt.Dsl.() -> kotlin.Unit): IMMsg.RankingContent =
  RankingContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

