// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializetransferContent")
public inline fun transferContent(block: TransferContentKt.Dsl.() -> kotlin.Unit): IMMsg.TransferContent =
  TransferContentKt.Dsl._create(IMMsg.TransferContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `TransferContent`
 */
public object TransferContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.TransferContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.TransferContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.TransferContent = _builder.build()

    /**
     * ```
     * 转接时间(毫秒)
     * ```
     *
     * `int64 transferTime = 1;`
     */
    public var transferTime: kotlin.Long
      @JvmName("getTransferTime")
      get() = _builder.transferTime
      @JvmName("setTransferTime")
      set(value) {
        _builder.transferTime = value
      }
    /**
     * ```
     * 转接时间(毫秒)
     * ```
     *
     * `int64 transferTime = 1;`
     */
    public fun clearTransferTime() {
      _builder.clearTransferTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.TransferContent.copy(block: TransferContentKt.Dsl.() -> kotlin.Unit): IMMsg.TransferContent =
  TransferContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

