// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.lbe.imsdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializeunsupportedContent")
public inline fun unsupportedContent(block: UnsupportedContentKt.Dsl.() -> kotlin.Unit): IMMsg.UnsupportedContent =
  UnsupportedContentKt.Dsl._create(IMMsg.UnsupportedContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `UnsupportedContent`
 */
public object UnsupportedContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.UnsupportedContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.UnsupportedContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.UnsupportedContent = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.UnsupportedContent.copy(block: UnsupportedContentKt.Dsl.() -> kotlin.Unit): IMMsg.UnsupportedContent =
  UnsupportedContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

