// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.chatapp.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializemsgType")
public inline fun msgType(block: MsgTypeKt.Dsl.() -> kotlin.Unit): IMMsg.MsgType =
  MsgTypeKt.Dsl._create(IMMsg.MsgType.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MsgType`
 */
public object MsgTypeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.MsgType.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.MsgType.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.MsgType = _builder.build()

    /**
     * `int32 messageType = 1;`
     */
    public var messageType: kotlin.Int
      @JvmName("getMessageType")
      get() = _builder.messageType
      @JvmName("setMessageType")
      set(value) {
        _builder.messageType = value
      }
    /**
     * `int32 messageType = 1;`
     */
    public fun clearMessageType() {
      _builder.clearMessageType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.MsgType.copy(block: MsgTypeKt.Dsl.() -> kotlin.Unit): IMMsg.MsgType =
  MsgTypeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

