// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.chatapp.service.proto.IMMsg

@kotlin.jvm.JvmName("-initializemsgEntity")
public inline fun msgEntity(block: MsgEntityKt.Dsl.() -> kotlin.Unit): IMMsg.MsgEntity =
  MsgEntityKt.Dsl._create(IMMsg.MsgEntity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MsgEntity`
 */
public object MsgEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.MsgEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.MsgEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.MsgEntity = _builder.build()

    /**
     * `.MsgType msgType = 1;`
     */
    public var msgType: IMMsg.MsgType
      @JvmName("getMsgType")
      get() = _builder.msgType
      @JvmName("setMsgType")
      set(value) {
        _builder.msgType = value
      }
    /**
     * `.MsgType msgType = 1;`
     */
    public fun clearMsgType() {
      _builder.clearMsgType()
    }
    /**
     * `.MsgType msgType = 1;`
     * @return Whether the msgType field is set.
     */
    public fun hasMsgType(): kotlin.Boolean {
      return _builder.hasMsgType()
    }

    public val MsgEntityKt.Dsl.msgTypeOrNull: IMMsg.MsgType?
      get() = _builder.msgTypeOrNull

    /**
     * `.Join join = 2;`
     */
    public var join: IMMsg.Join
      @JvmName("getJoin")
      get() = _builder.join
      @JvmName("setJoin")
      set(value) {
        _builder.join = value
      }
    /**
     * `.Join join = 2;`
     */
    public fun clearJoin() {
      _builder.clearJoin()
    }
    /**
     * `.Join join = 2;`
     * @return Whether the join field is set.
     */
    public fun hasJoin(): kotlin.Boolean {
      return _builder.hasJoin()
    }

    public val MsgEntityKt.Dsl.joinOrNull: IMMsg.Join?
      get() = _builder.joinOrNull

    /**
     * `.TalkText talkText = 3;`
     */
    public var talkText: IMMsg.TalkText
      @JvmName("getTalkText")
      get() = _builder.talkText
      @JvmName("setTalkText")
      set(value) {
        _builder.talkText = value
      }
    /**
     * `.TalkText talkText = 3;`
     */
    public fun clearTalkText() {
      _builder.clearTalkText()
    }
    /**
     * `.TalkText talkText = 3;`
     * @return Whether the talkText field is set.
     */
    public fun hasTalkText(): kotlin.Boolean {
      return _builder.hasTalkText()
    }

    public val MsgEntityKt.Dsl.talkTextOrNull: IMMsg.TalkText?
      get() = _builder.talkTextOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.MsgEntity.copy(block: MsgEntityKt.Dsl.() -> kotlin.Unit): IMMsg.MsgEntity =
  MsgEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val IMMsg.MsgEntityOrBuilder.msgTypeOrNull: IMMsg.MsgType?
  get() = if (hasMsgType()) getMsgType() else null

public val IMMsg.MsgEntityOrBuilder.joinOrNull: IMMsg.Join?
  get() = if (hasJoin()) getJoin() else null

public val IMMsg.MsgEntityOrBuilder.talkTextOrNull: IMMsg.TalkText?
  get() = if (hasTalkText()) getTalkText() else null

